# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('facturacion', '0001_initial'),
        ('impuestos', '0001_initial'),
        ('remuneraciones', '0001_initial'),
        ('rendiciones', '0001_initial'),
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('CONTROL', 'Control'), ('OTRO', 'Otro')], max_length=15)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='finanzas.categoriafinanciera')),
            ],
            options={
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ObligacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='finanzas.categoriafinanciera')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones_financieras', to='core.centrocosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CierreFinancieroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CALCULADO', 'Calculado'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=15)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_financieros_realizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('anio', 'mes'), name='uq_cierre_financiero'), models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='ck_cierre_fin_mes')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('descripcion', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('REMUNERACION', 'Remuneración'), ('RENDICION', 'Rendición'), ('FACTURACION', 'Facturación'), ('COMPRA', 'Compra'), ('IMPUESTO', 'Impuesto'), ('OTRO', 'Otro')], default='MANUAL', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('archivo_respaldo', models.FileField(blank=True, null=True, upload_to='finanzas/movimientos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas.categoriafinanciera')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='core.centrocosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='facturacion.documentocompra')),
                ('documento_tributario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='facturacion.documentotributario')),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='remuneraciones.liquidacionmensual')),
                ('periodo_impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='impuestos.periodoimpuesto')),
                ('rendicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='rendiciones.rendicion')),
                ('trabajador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_financieros', to='rrhh.trabajador')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha', 'tipo'], name='idx_mov_fin_fecha_tipo')],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_mov_fin_monto')],
            },
        ),
        migrations.CreateModel(
            name='PagoObligacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.obligacionfinanciera')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pago_obligacion_monto')],
            },
        ),
    ]
