# Generated by Django 5.2.17 on 2026-08-28 21:56

from django.db import migrations, models


def completar_clasificacion(apps, schema_editor):
    Categoria = apps.get_model("finanzas", "CategoriaFinanciera")
    Categoria.objects.filter(codigo__in=["ING_CLIENTES", "EGR_REMUNERACIONES", "EGR_PROVEEDORES", "EGR_RENDICIONES", "EGR_IMPUESTOS", "EGR_BANCARIOS", "ING_OTROS", "EGR_OTROS"]).update(grupo_flujo="OPERACION", afecta_resultado=True)
    datos = [
        ("ING_APORTE_CAPITAL", "Aporte de capital", "INGRESO", "FINANCIAMIENTO", False),
        ("EGR_RETIRO_CAPITAL", "Retiro de capital", "EGRESO", "FINANCIAMIENTO", False),
        ("ING_FINANCIAMIENTO", "Financiamiento recibido", "INGRESO", "FINANCIAMIENTO", False),
        ("EGR_PAGO_FINANCIAMIENTO", "Pago de financiamiento", "EGRESO", "FINANCIAMIENTO", False),
        ("EGR_INVERSION", "Inversiones", "EGRESO", "INVERSION", False),
    ]
    for codigo, nombre, tipo, grupo, afecta in datos:
        Categoria.objects.update_or_create(codigo=codigo, defaults={"nombre": nombre, "tipo": tipo, "grupo_flujo": grupo, "afecta_resultado": afecta, "permite_manual": True, "activo": True})


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_fin005_anulacion_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriafinanciera',
            name='afecta_resultado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriafinanciera',
            name='grupo_flujo',
            field=models.CharField(choices=[('OPERACION', 'Operación'), ('INVERSION', 'Inversión'), ('FINANCIAMIENTO', 'Financiamiento')], default='OPERACION', max_length=20),
        ),
        migrations.RunPython(completar_clasificacion, migrations.RunPython.noop),
    ]
