# Generated by Django 5.2.17 on 2026-08-28 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_categoriafinanciera_afecta_resultado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoobligacionfinanciera',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagoobligacionfinanciera',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagoobligacionfinanciera',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_obligacion_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagoobligacionfinanciera',
            name='medio_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pagoobligacionfinanciera',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagoobligacionfinanciera',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
