# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_original', models.FileField(upload_to='excel/importaciones/%Y/%m/')),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('hash_archivo', models.CharField(blank=True, db_index=True, max_length=128)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('COMPLETADA_CON_ERRORES', 'Completada con errores'), ('ERROR', 'Error')], default='PENDIENTE', max_length=30)),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportacionFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('hoja', models.CharField(max_length=100)),
                ('fila', models.PositiveIntegerField()),
                ('modelo_destino', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('IMPORTADA', 'Importada'), ('OMITIDA', 'Omitida'), ('ERROR', 'Error')], max_length=15)),
                ('datos_originales', models.JSONField(blank=True, default=dict)),
                ('mensaje', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='integracion_excel.importacionexcel')),
            ],
            options={
                'ordering': ['importacion', 'hoja', 'fila'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('NOMINA', 'Nómina de remuneraciones'), ('PAGOS_GENERALES', 'Planilla de pagos generales'), ('OTRO', 'Otro')], max_length=30)),
                ('archivo', models.FileField(upload_to='excel/plantillas/')),
                ('version', models.CharField(default='1', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='importacionexcel',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones', to='integracion_excel.plantillaexcel'),
        ),
        migrations.CreateModel(
            name='ExportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='excel/exportaciones/%Y/%m/')),
                ('iniciado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exportaciones', to='integracion_excel.plantillaexcel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapeoExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=100)),
                ('hoja', models.CharField(max_length=100)),
                ('tipo_mapeo', models.CharField(choices=[('CELDA', 'Celda'), ('RANGO', 'Rango'), ('TABLA', 'Tabla'), ('COLUMNA', 'Columna'), ('GRAFICO', 'Gráfico')], max_length=15)),
                ('referencia_excel', models.CharField(max_length=150)),
                ('origen', models.CharField(help_text='Clave lógica de origen. Ejemplo: remuneraciones.total_mes', max_length=250)),
                ('formato_excel', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos', to='integracion_excel.plantillaexcel')),
            ],
            options={
                'ordering': ['plantilla', 'hoja', 'codigo'],
                'constraints': [models.UniqueConstraint(fields=('plantilla', 'codigo'), name='uq_mapeo_excel_codigo')],
            },
        ),
    ]
