# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(editable=False)),
                ('fecha_fin', models.DateField(editable=False)),
                ('iva_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('iva_compras', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('subtotal_iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('neto_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tasa_ppm_snapshot', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('total_ppm', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('monto_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADO', 'Calculado'), ('DECLARADO', 'Declarado'), ('PAGADO', 'Pagado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=15)),
                ('calculado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_impuestos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='PagoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='impuestos/pagos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='impuestos.periodoimpuesto')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('IVA_VENTA', 'IVA venta'), ('IVA_COMPRA', 'IVA compra')], max_length=20)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_impuesto', to='facturacion.documentocompra')),
                ('documento_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_impuesto', to='facturacion.documentotributario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='impuestos.periodoimpuesto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='periodoimpuesto',
            constraint=models.UniqueConstraint(fields=('anio', 'mes'), name='uq_periodo_impuesto'),
        ),
        migrations.AddConstraint(
            model_name='periodoimpuesto',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='ck_periodo_impuesto_mes'),
        ),
        migrations.AddConstraint(
            model_name='pagoimpuesto',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pago_impuesto_monto'),
        ),
        migrations.AddConstraint(
            model_name='detalleimpuesto',
            constraint=models.UniqueConstraint(fields=('periodo', 'documento_venta'), name='uq_imp_periodo_doc_venta'),
        ),
        migrations.AddConstraint(
            model_name='detalleimpuesto',
            constraint=models.UniqueConstraint(fields=('periodo', 'documento_compra'), name='uq_imp_periodo_doc_compra'),
        ),
    ]
