CONCEPTOS_INICIALES = [
    {
        "codigo": "SUELDO_BASE",
        "nombre": "Sueldo base",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 10,
    },
    {
        "codigo": "HORAS_EXTRA",
        "nombre": "Horas extraordinarias",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 20,
    },
    {
        "codigo": "AGUINALDO",
        "nombre": "Aguinaldo",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 30,
    },
    {
        "codigo": "ALOJAMIENTO",
        "nombre": "Alojamiento",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 40,
    },
    {
        "codigo": "MOVILIZACION",
        "nombre": "Movilización",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": True,
        "editable": True,
        "orden": 50,
    },
    {
        "codigo": "COLACION",
        "nombre": "Colación",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": True,
        "editable": True,
        "orden": 60,
    },
    {
        "codigo": "DESGASTE_HERRAMIENTAS",
        "nombre": "Desgaste de herramientas",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": True,
        "editable": True,
        "orden": 70,
    },
    {
        "codigo": "BONO_PRODUCCION",
        "nombre": "Bono de producción",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 80,
    },
    {
        "codigo": "BONO_ASISTENCIA",
        "nombre": "Bono de asistencia",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 90,
    },
    {
        "codigo": "FINIQUITO",
        "nombre": "Finiquito",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 100,
    },
    {
        "codigo": "ANTICIPO",
        "nombre": "Anticipo",
        "tipo": "DESCUENTO",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 200,
    },
    {
        "codigo": "PRESTAMO_ENTREGADO",
        "nombre": "Préstamo entregado",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 205,
        "descripcion": (
            "Entrega de dinero al trabajador. No usar el nombre Excel "
            "PRESTAMOS: el signo lo da este código, no el texto."
        ),
    },
    {
        "codigo": "PRESTAMO_DESCUENTO",
        "nombre": "Descuento de préstamo",
        "tipo": "DESCUENTO",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 210,
    },
    {
        "codigo": "INASISTENCIA",
        "nombre": "Inasistencia",
        "tipo": "DESCUENTO",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 220,
    },
]

# Componentes de la tercera tabla Excel (costo trabajador). Lista configurable.
# codigo_origen → ConceptoRemuneracion; vacío + incluye_en_total=False = TOTAL_LIQUIDADO.
CONCEPTOS_COSTO_INICIALES = [
    {
        "codigo": "SUELDO_BASE",
        "nombre": "Sueldo base",
        "codigo_origen": "SUELDO_BASE",
        "incluye_en_total": True,
        "orden": 10,
    },
    {
        "codigo": "DESGASTE_HERRAMIENTAS",
        "nombre": "Desgaste de herramientas",
        "codigo_origen": "DESGASTE_HERRAMIENTAS",
        "incluye_en_total": True,
        "orden": 20,
    },
    {
        "codigo": "MOVILIZACION",
        "nombre": "Movilización",
        "codigo_origen": "MOVILIZACION",
        "incluye_en_total": True,
        "orden": 30,
    },
    {
        "codigo": "COLACION",
        "nombre": "Colación",
        "codigo_origen": "COLACION",
        "incluye_en_total": True,
        "orden": 40,
    },
    {
        "codigo": "ALOJAMIENTO",
        "nombre": "Alojamiento",
        "codigo_origen": "ALOJAMIENTO",
        "incluye_en_total": True,
        "orden": 50,
    },
    {
        "codigo": "HHEX",
        "nombre": "Horas extraordinarias (HHEX)",
        "codigo_origen": "HORAS_EXTRA",
        "incluye_en_total": True,
        "orden": 60,
        "descripcion": "Equivalente Excel HHEX; monto desde HORAS_EXTRA de la liquidación.",
    },
    {
        "codigo": "BONO_PRODUCCION",
        "nombre": "Bonos de producción",
        "codigo_origen": "BONO_PRODUCCION",
        "incluye_en_total": True,
        "orden": 70,
    },
    {
        "codigo": "BONO_ASISTENCIA",
        "nombre": "Bono de asistencia",
        "codigo_origen": "BONO_ASISTENCIA",
        "incluye_en_total": True,
        "orden": 80,
    },
    {
        "codigo": "TOTAL_LIQUIDADO",
        "nombre": "Total liquidado",
        "codigo_origen": "",
        "incluye_en_total": False,
        "orden": 900,
        "descripcion": (
            "Referencia de lo que recibe el trabajador "
            "(liquidacion.total_liquidado). No suma al costo."
        ),
    },
]
