CONCEPTOS_INICIALES = [
    {
        "codigo": "SUELDO_BASE",
        "nombre": "Sueldo base",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 10,
    },
    {
        "codigo": "HORAS_EXTRA",
        "nombre": "Horas extraordinarias",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 20,
    },
    {
        "codigo": "AGUINALDO",
        "nombre": "Aguinaldo",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 30,
    },
    {
        "codigo": "ALOJAMIENTO",
        "nombre": "Alojamiento",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 40,
    },
    {
        "codigo": "MOVILIZACION",
        "nombre": "Movilización",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": True,
        "editable": True,
        "orden": 50,
    },
    {
        "codigo": "COLACION",
        "nombre": "Colación",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": True,
        "editable": True,
        "orden": 60,
    },
    {
        "codigo": "DESGASTE_HERRAMIENTAS",
        "nombre": "Desgaste de herramientas",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": True,
        "editable": True,
        "orden": 70,
    },
    {
        "codigo": "BONO_PRODUCCION",
        "nombre": "Bono de producción",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 80,
    },
    {
        "codigo": "BONO_ASISTENCIA",
        "nombre": "Bono de asistencia",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 90,
    },
    {
        "codigo": "FINIQUITO",
        "nombre": "Finiquito",
        "tipo": "HABER",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 100,
    },
    {
        "codigo": "ANTICIPO",
        "nombre": "Anticipo",
        "tipo": "DESCUENTO",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 200,
    },
    {
        "codigo": "PRESTAMO_ENTREGADO",
        "nombre": "Préstamo entregado",
        "tipo": "HABER",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 205,
        "descripcion": (
            "Entrega de dinero al trabajador. No usar el nombre Excel "
            "PRESTAMOS: el signo lo da este código, no el texto."
        ),
    },
    {
        "codigo": "PRESTAMO_DESCUENTO",
        "nombre": "Descuento de préstamo",
        "tipo": "DESCUENTO",
        "naturaleza_calculo": "MANUAL",
        "proporcional_dias": False,
        "editable": True,
        "orden": 210,
    },
    {
        "codigo": "INASISTENCIA",
        "nombre": "Inasistencia",
        "tipo": "DESCUENTO",
        "naturaleza_calculo": "AUTOMATICO",
        "proporcional_dias": False,
        "editable": False,
        "orden": 220,
    },
]
