from django.urls import path

from remuneraciones import views

app_name = "remuneraciones"

urlpatterns = [
    path(
        "periodos/",
        views.PeriodoListView.as_view(),
        name="periodo_lista",
    ),
    path(
        "periodos/nuevo/",
        views.PeriodoCreateView.as_view(),
        name="periodo_crear",
    ),
    path(
        "periodos/<int:pk>/",
        views.PeriodoDetailView.as_view(),
        name="periodo_detalle",
    ),
    path(
        "periodos/<int:pk>/editar/",
        views.PeriodoUpdateView.as_view(),
        name="periodo_editar",
    ),
    path(
        "periodos/<int:pk>/abrir/",
        views.PeriodoAbrirView.as_view(),
        name="periodo_abrir",
    ),
    path(
        "periodos/<int:pk>/calcular/",
        views.PeriodoCalcularView.as_view(),
        name="periodo_calcular",
    ),
    path(
        "periodos/<int:pk>/validar/",
        views.PeriodoValidarView.as_view(),
        name="periodo_validar",
    ),
    path(
        "periodos/<int:pk>/cerrar/",
        views.PeriodoCerrarView.as_view(),
        name="periodo_cerrar",
    ),
    path(
        "periodos/<int:pk>/reabrir/",
        views.PeriodoReabrirView.as_view(),
        name="periodo_reabrir",
    ),
    path(
        "conceptos/",
        views.ConceptoListView.as_view(),
        name="concepto_lista",
    ),
    path(
        "conceptos/nuevo/",
        views.ConceptoCreateView.as_view(),
        name="concepto_crear",
    ),
    path(
        "conceptos/<int:pk>/editar/",
        views.ConceptoUpdateView.as_view(),
        name="concepto_editar",
    ),
    path(
        "horas-extra/",
        views.HoraExtraListView.as_view(),
        name="hora_extra_lista",
    ),
    path(
        "horas-extra/nuevo/",
        views.HoraExtraCreateView.as_view(),
        name="hora_extra_crear",
    ),
    path(
        "horas-extra/<int:pk>/editar/",
        views.HoraExtraUpdateView.as_view(),
        name="hora_extra_editar",
    ),
    path(
        "horas-extra/<int:pk>/borrar/",
        views.HoraExtraDeleteView.as_view(),
        name="hora_extra_borrar",
    ),
    path(
        "periodos/<int:periodo_id>/horas-extra/",
        views.PeriodoHorasExtraView.as_view(),
        name="periodo_horas_extra",
    ),
    path(
        "trabajadores/<int:trabajador_id>/horas-extra/",
        views.HoraExtraListView.as_view(),
        name="trabajador_horas_extra",
    ),
    path(
        "trabajadores/<int:trabajador_id>/horas-extra/nuevo/",
        views.HoraExtraCreateView.as_view(),
        name="trabajador_hora_extra_crear",
    ),
    path(
        "movimientos/",
        views.MovimientoListView.as_view(),
        name="movimiento_lista",
    ),
    path(
        "movimientos/nuevo/",
        views.MovimientoCreateView.as_view(),
        name="movimiento_crear",
    ),
    path(
        "movimientos/<int:pk>/editar/",
        views.MovimientoUpdateView.as_view(),
        name="movimiento_editar",
    ),
    path(
        "movimientos/<int:pk>/borrar/",
        views.MovimientoDeleteView.as_view(),
        name="movimiento_borrar",
    ),
    path(
        "periodos/<int:periodo_id>/movimientos/",
        views.PeriodoMovimientosView.as_view(),
        name="periodo_movimientos",
    ),
    path(
        "trabajadores/<int:trabajador_id>/movimientos/",
        views.MovimientoListView.as_view(),
        name="trabajador_movimientos",
    ),
    path(
        "trabajadores/<int:trabajador_id>/movimientos/nuevo/",
        views.MovimientoCreateView.as_view(),
        name="trabajador_movimiento_crear",
    ),
    path(
        "finiquitos/",
        views.FiniquitoListView.as_view(),
        name="finiquito_lista",
    ),
    path(
        "finiquitos/nuevo/",
        views.FiniquitoCreateView.as_view(),
        name="finiquito_crear",
    ),
    path(
        "finiquitos/<int:pk>/",
        views.FiniquitoDetailView.as_view(),
        name="finiquito_detalle",
    ),
    path(
        "finiquitos/<int:pk>/editar/",
        views.FiniquitoUpdateView.as_view(),
        name="finiquito_editar",
    ),
    path(
        "finiquitos/<int:pk>/borrar/",
        views.FiniquitoDeleteView.as_view(),
        name="finiquito_borrar",
    ),
    path(
        "finiquitos/<int:pk>/validar/",
        views.FiniquitoAccionView.as_view(accion="validar"),
        name="finiquito_validar",
    ),
    path(
        "finiquitos/<int:pk>/pagar/",
        views.FiniquitoAccionView.as_view(accion="pagar"),
        name="finiquito_pagar",
    ),
    path(
        "finiquitos/<int:pk>/anular/",
        views.FiniquitoAccionView.as_view(accion="anular"),
        name="finiquito_anular",
    ),
    path(
        "finiquitos/<int:pk>/terminar-contrato/",
        views.FiniquitoAccionView.as_view(accion="terminar_contrato"),
        name="finiquito_terminar_contrato",
    ),
    path(
        "periodos/<int:periodo_id>/finiquitos/",
        views.FiniquitoListView.as_view(),
        name="periodo_finiquitos",
    ),
    path(
        "periodos/<int:periodo_id>/finiquitos/nuevo/",
        views.FiniquitoCreateView.as_view(),
        name="periodo_finiquito_crear",
    ),
    path(
        "trabajadores/<int:trabajador_id>/finiquitos/",
        views.FiniquitoListView.as_view(),
        name="trabajador_finiquitos",
    ),
    path(
        "trabajadores/<int:trabajador_id>/finiquitos/nuevo/",
        views.FiniquitoCreateView.as_view(),
        name="trabajador_finiquito_crear",
    ),
    path(
        "liquidaciones/",
        views.LiquidacionListView.as_view(),
        name="liquidacion_lista",
    ),
    path(
        "liquidaciones/<int:pk>/",
        views.LiquidacionDetailView.as_view(),
        name="liquidacion_detalle",
    ),
    path(
        "liquidaciones/<int:pk>/calcular/",
        views.LiquidacionCalcularView.as_view(),
        name="liquidacion_calcular",
    ),
    path(
        "liquidaciones/<int:pk>/validar/",
        views.LiquidacionAccionView.as_view(accion="validar"),
        name="liquidacion_validar",
    ),
    path(
        "liquidaciones/<int:pk>/anular/",
        views.LiquidacionAccionView.as_view(accion="anular"),
        name="liquidacion_anular",
    ),
    path(
        "liquidaciones/<int:pk>/pagar/",
        views.LiquidacionAccionView.as_view(accion="pagar"),
        name="liquidacion_pagar",
    ),
    path(
        "liquidaciones/<int:pk>/pagos/",
        views.LiquidacionPagoView.as_view(),
        name="liquidacion_pago",
    ),
    path(
        "periodos/<int:periodo_id>/liquidaciones/",
        views.LiquidacionListView.as_view(),
        name="periodo_liquidaciones",
    ),
    path(
        "trabajadores/<int:trabajador_id>/liquidaciones/",
        views.LiquidacionListView.as_view(),
        name="trabajador_liquidaciones",
    ),
    path(
        "costos/",
        views.CostoListView.as_view(),
        name="costo_lista",
    ),
    path(
        "costos/<int:pk>/",
        views.CostoDetailView.as_view(),
        name="costo_detalle",
    ),
    path(
        "liquidaciones/<int:pk>/generar-costo/",
        views.CostoGenerarLiquidacionView.as_view(),
        name="liquidacion_generar_costo",
    ),
    path(
        "periodos/<int:pk>/generar-costos/",
        views.PeriodoGenerarCostosView.as_view(),
        name="periodo_generar_costos",
    ),
    path(
        "periodos/<int:periodo_id>/costos/",
        views.CostoListView.as_view(),
        name="periodo_costos",
    ),
    path(
        "trabajadores/<int:trabajador_id>/costos/",
        views.CostoListView.as_view(),
        name="trabajador_costos",
    ),
]
