from django.urls import path

from remuneraciones import views

app_name = "remuneraciones"

urlpatterns = [
    path(
        "periodos/",
        views.PeriodoListView.as_view(),
        name="periodo_lista",
    ),
    path(
        "periodos/nuevo/",
        views.PeriodoCreateView.as_view(),
        name="periodo_crear",
    ),
    path(
        "periodos/<int:pk>/",
        views.PeriodoDetailView.as_view(),
        name="periodo_detalle",
    ),
    path(
        "periodos/<int:pk>/editar/",
        views.PeriodoUpdateView.as_view(),
        name="periodo_editar",
    ),
    path(
        "periodos/<int:pk>/abrir/",
        views.PeriodoAbrirView.as_view(),
        name="periodo_abrir",
    ),
    path(
        "periodos/<int:pk>/calcular/",
        views.PeriodoCalcularView.as_view(),
        name="periodo_calcular",
    ),
    path(
        "periodos/<int:pk>/validar/",
        views.PeriodoValidarView.as_view(),
        name="periodo_validar",
    ),
    path(
        "periodos/<int:pk>/cerrar/",
        views.PeriodoCerrarView.as_view(),
        name="periodo_cerrar",
    ),
    path(
        "periodos/<int:pk>/reabrir/",
        views.PeriodoReabrirView.as_view(),
        name="periodo_reabrir",
    ),
    path(
        "conceptos/",
        views.ConceptoListView.as_view(),
        name="concepto_lista",
    ),
    path(
        "conceptos/nuevo/",
        views.ConceptoCreateView.as_view(),
        name="concepto_crear",
    ),
    path(
        "conceptos/<int:pk>/editar/",
        views.ConceptoUpdateView.as_view(),
        name="concepto_editar",
    ),
    path(
        "horas-extra/",
        views.HoraExtraListView.as_view(),
        name="hora_extra_lista",
    ),
    path(
        "horas-extra/nuevo/",
        views.HoraExtraCreateView.as_view(),
        name="hora_extra_crear",
    ),
    path(
        "horas-extra/<int:pk>/editar/",
        views.HoraExtraUpdateView.as_view(),
        name="hora_extra_editar",
    ),
    path(
        "horas-extra/<int:pk>/borrar/",
        views.HoraExtraDeleteView.as_view(),
        name="hora_extra_borrar",
    ),
    path(
        "periodos/<int:periodo_id>/horas-extra/",
        views.PeriodoHorasExtraView.as_view(),
        name="periodo_horas_extra",
    ),
    path(
        "trabajadores/<int:trabajador_id>/horas-extra/",
        views.HoraExtraListView.as_view(),
        name="trabajador_horas_extra",
    ),
    path(
        "trabajadores/<int:trabajador_id>/horas-extra/nuevo/",
        views.HoraExtraCreateView.as_view(),
        name="trabajador_hora_extra_crear",
    ),
]
