# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('total_declarado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PRESENTADA', 'Presentada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendiciones', to='rrhh.trabajador')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura'), ('COMPROBANTE', 'Comprobante'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('archivo', models.FileField(upload_to='rendiciones/%Y/%m/')),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rendiciones.rendicion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RendicionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(blank=True, max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_rendicion', to='core.centrocosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='rendiciones.rendicion')),
            ],
            options={
                'ordering': ['rendicion', 'centro_costo__codigo'],
            },
        ),
        migrations.AddConstraint(
            model_name='rendicion',
            constraint=models.CheckConstraint(condition=models.Q(('total_declarado__gte', 0)), name='ck_rendicion_total'),
        ),
        migrations.AddConstraint(
            model_name='rendiciondetalle',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_rendicion_detalle_monto'),
        ),
    ]
