# Generated by Django 5.2.17 on 2026-08-25 17:16

import rendiciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorendicion',
            name='archivo',
            field=models.FileField(upload_to=rendiciones.models.documento_rendicion_upload_to),
        ),
    ]
