# Generated by Django 5.2.17 on 2026-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0002_documento_upload_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendicion',
            options={'ordering': ['-fecha'], 'permissions': [('presentar_rendicion', 'Puede presentar rendiciones'), ('aprobar_rendicion', 'Puede aprobar rendiciones'), ('rechazar_rendicion', 'Puede rechazar rendiciones'), ('anular_rendicion', 'Puede anular rendiciones')]},
        ),
        migrations.AddField(
            model_name='rendicion',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
    ]
