# Generated by Django 5.2.17 on 2026-08-28 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_lineas_base(apps, schema_editor):
    Linea = apps.get_model("balance", "LineaBalance")
    datos = [
        ("CAJA", "Caja", "LIQUIDEZ", "SALDO", "FIN_SALDO", False),
        ("CUENTAS_POR_COBRAR", "Cuentas por cobrar", "COBRAR", "SALDO", "FAC_COBROS", False),
        ("PROVEEDORES", "Proveedores por pagar", "OBLIGACIONES", "SALDO", "COM_SALDOS", False),
        ("REMUNERACIONES", "Remuneraciones por pagar", "OBLIGACIONES", "SALDO", "REM_SALDOS", False),
        ("IMPUESTOS", "Impuestos por pagar", "OBLIGACIONES", "SALDO", "IMP_SALDOS", False),
        ("IVA", "IVA", "TRIBUTARIA", "TRIBUTARIO", "IMP_IVA", False),
        ("PPM", "PPM", "TRIBUTARIA", "TRIBUTARIO", "IMP_PPM", False),
        ("INGRESOS", "Ingresos documentales", "RESULTADO", "RESULTADO", "FAC_NETO", False),
        ("COSTOS_OPERACIONALES", "Costos operacionales", "RESULTADO", "RESULTADO", "FIN_OPERACION", False),
        ("APORTES_CAPITAL", "Aportes de socio", "FINANCIAMIENTO", "FINANCIAMIENTO", "FIN_APORTES", False),
        ("CAPITAL_POR_ENTERAR", "Capital por enterar", "FINANCIAMIENTO", "AJUSTE", "AJUSTE_CAPITAL", True),
        ("EXCEL_MATERIALES", "Materiales", "EXCEL", "COMPRA", "MAT_MATERIALES", False),
        ("EXCEL_COMBUSTIBLE", "Combustible", "EXCEL", "COMPRA", "GAS_COMBUSTIBLE", False),
        ("EXCEL_FLETES", "Fletes", "EXCEL", "COMPRA", "SER_FLETES", False),
        ("EXCEL_SEGUROS", "Seguros", "EXCEL", "COMPRA", "SER_SEGUROS", False),
        ("EXCEL_ASESORIAS", "Asesorías", "EXCEL", "COMPRA", "SER_ASESORIAS", False),
        ("EXCEL_ARRIENDOS", "Arriendos", "EXCEL", "COMPRA", "ARR_MAQ_VEHICULOS", False),
        ("EXCEL_GASTOS_GENERALES", "Gastos generales", "EXCEL", "COMPRA", "GAS_GENERALES", False),
        ("EXCEL_INGRESOS", "Ingresos", "EXCEL", "RESULTADO", "FAC_TOTAL", False),
    ]
    for orden, (codigo, nombre, seccion, tipo, fuente, ajuste) in enumerate(datos, 1):
        Linea.objects.update_or_create(codigo=codigo, defaults={"nombre": nombre, "seccion": seccion, "tipo": tipo, "fuente": fuente, "codigo_fuente": fuente, "orden": orden, "permite_ajuste": ajuste, "activa": True})


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('seccion', models.CharField(choices=[('LIQUIDEZ', 'Liquidez'), ('COBRAR', 'Cuentas por cobrar'), ('OBLIGACIONES', 'Obligaciones'), ('TRIBUTARIA', 'Posición tributaria'), ('RESULTADO', 'Resultado de gestión'), ('FINANCIAMIENTO', 'Financiamiento / capital'), ('EXCEL', 'Equivalencia Excel')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(max_length=30)),
                ('fuente', models.CharField(max_length=50)),
                ('codigo_fuente', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('permite_ajuste', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seccion', 'orden', 'codigo'],
            },
        ),
        migrations.RunPython(crear_lineas_base, migrations.RunPython.noop),
    ]
