# Generated by Django 5.2.17 on 2026-08-28 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_corte', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('CERRADO', 'Cerrado'), ('REABIERTO', 'Reabierto')], default='CERRADO', max_length=12)),
                ('caja', models.DecimalField(decimal_places=2, max_digits=16)),
                ('cuentas_por_cobrar', models.DecimalField(decimal_places=2, max_digits=16)),
                ('obligaciones', models.DecimalField(decimal_places=2, max_digits=16)),
                ('resultado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('posicion_disponible', models.DecimalField(decimal_places=2, max_digits=16)),
                ('resumen_fuentes', models.JSONField(default=dict)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
