# Generated by Django 5.2.17 on 2026-08-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoCostoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento'), ('INFORMATIVO', 'Informativo')], max_length=15)),
                ('naturaleza_calculo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('MIXTO', 'Mixto')], default='MANUAL', max_length=15)),
                ('proporcional_dias', models.BooleanField(default=False)),
                ('editable', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CALCULADA', 'Calculada'), ('VALIDADA', 'Validada'), ('PAGADA', 'Pagada'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('sueldo_base_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cargo_codigo_snapshot', models.CharField(blank=True, max_length=30)),
                ('cargo_nombre_snapshot', models.CharField(blank=True, max_length=120)),
                ('centro_costo_codigo_snapshot', models.CharField(blank=True, max_length=30)),
                ('centro_costo_nombre_snapshot', models.CharField(blank=True, max_length=150)),
                ('dias_fallados', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dias_trabajados', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('valor_dia', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('horas_extra_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('valor_hora_extra', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('monto_horas_extra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_haberes', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_liquidado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('version_calculo', models.CharField(default='1.0', max_length=30)),
                ('calculado_en', models.DateTimeField(blank=True, null=True)),
                ('requiere_recalculo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='core.centrocosto')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='rrhh.contrato')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='rrhh.trabajador')),
            ],
            options={
                'ordering': ['-periodo__anio', '-periodo__mes', 'trabajador__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='CostoTrabajadorPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('centro_costo_codigo_snapshot', models.CharField(blank=True, max_length=30)),
                ('centro_costo_nombre_snapshot', models.CharField(blank=True, max_length=150)),
                ('dias_trabajados', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('calculado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costos_trabajadores', to='core.centrocosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo_trabajador', to='remuneraciones.liquidacionmensual')),
            ],
            options={
                'ordering': ['liquidacion'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('fecha_inicio', models.DateField(editable=False)),
                ('fecha_fin', models.DateField(editable=False)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTO', 'Abierto'), ('CALCULADO', 'Calculado'), ('VALIDADO', 'Validado'), ('CERRADO', 'Cerrado')], default='BORRADOR', max_length=20)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_reapertura', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_remuneracion_cerrados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.AddField(
            model_name='liquidacionmensual',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='remuneraciones.periodoremuneracion'),
        ),
        migrations.CreateModel(
            name='HoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(db_index=True)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actividad', models.TextField(blank=True)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORTADO_EXCEL', 'Importado desde Excel')], default='MANUAL', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extra', to='rrhh.trabajador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horas_extra', to='remuneraciones.periodoremuneracion')),
            ],
            options={
                'ordering': ['-fecha', 'trabajador__nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Finiquito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('VALIDADO', 'Validado'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='remuneraciones/finiquitos/%Y/%m/')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finiquitos', to='rrhh.contrato')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finiquitos', to='rrhh.trabajador')),
                ('liquidacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finiquitos', to='remuneraciones.liquidacionmensual')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finiquitos', to='remuneraciones.periodoremuneracion')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CostoTrabajadorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='remuneraciones.conceptocostotrabajador')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('costo_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='remuneraciones.costotrabajadorperiodo')),
            ],
            options={
                'ordering': ['costo_trabajador', 'concepto__orden'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_costo_trab_det_monto')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('CALCULADO', 'Calculado'), ('IMPORTADO_EXCEL', 'Importado desde Excel')], default='MANUAL', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('generado_automaticamente', models.BooleanField(default=False)),
                ('bloqueado', models.BooleanField(default=False)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='remuneraciones.conceptoremuneracion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='remuneraciones.liquidacionmensual')),
            ],
            options={
                'ordering': ['liquidacion', 'concepto__orden'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_movimiento_rem_monto')],
            },
        ),
        migrations.CreateModel(
            name='PagoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('medio_pago', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='remuneraciones.liquidacionmensual')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pago_remuneracion_monto')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodoremuneracion',
            constraint=models.UniqueConstraint(fields=('anio', 'mes'), name='uq_periodo_remuneracion'),
        ),
        migrations.AddConstraint(
            model_name='periodoremuneracion',
            constraint=models.CheckConstraint(condition=models.Q(('mes__gte', 1), ('mes__lte', 12)), name='ck_periodo_remuneracion_mes'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionmensual',
            constraint=models.UniqueConstraint(fields=('periodo', 'trabajador'), name='uq_liquidacion_periodo_trabajador'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionmensual',
            constraint=models.CheckConstraint(condition=models.Q(('dias_fallados__gte', 0)), name='ck_liquidacion_dias_fallados'),
        ),
        migrations.AddConstraint(
            model_name='liquidacionmensual',
            constraint=models.CheckConstraint(condition=models.Q(('dias_trabajados__gte', 0)), name='ck_liquidacion_dias_trabajados'),
        ),
        migrations.AddConstraint(
            model_name='horaextra',
            constraint=models.CheckConstraint(condition=models.Q(('horas__gt', 0)), name='ck_hora_extra_horas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='finiquito',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_finiquito_monto'),
        ),
    ]
