# Generated by Django 5.2.17 on 2026-08-24 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodoremuneracion',
            options={'ordering': ['-anio', '-mes'], 'verbose_name': 'período de remuneración', 'verbose_name_plural': 'períodos de remuneración'},
        ),
        migrations.AlterField(
            model_name='periodoremuneracion',
            name='mes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
