# Generated by Django 5.2.17 on 2026-08-25 13:41

import remuneraciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneraciones', '0004_prestamo_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finiquito',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=remuneraciones.models.finiquito_upload_to),
        ),
        migrations.AlterField(
            model_name='finiquito',
            name='motivo',
            field=models.CharField(blank=True, choices=[('MUTUO_ACUERDO', 'Mutuo acuerdo'), ('RENUNCIA', 'Renuncia'), ('DESAHUCIO', 'Desahucio'), ('NECESIDADES_EMPRESA', 'Necesidades de la empresa'), ('TERMINO_PLAZO', 'Término de plazo'), ('TERMINO_OBRA', 'Término de obra o faena'), ('OTRO', 'Otro')], default='OTRO', max_length=30),
        ),
    ]
