# Generated by Django 5.2.17 on 2026-08-25 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneraciones', '0005_finiquito_motivo_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptocostotrabajador',
            name='codigo_origen',
            field=models.CharField(blank=True, help_text='Código de ConceptoRemuneracion del cual se toma el monto. Vacío para totales de referencia (p. ej. TOTAL_LIQUIDADO).', max_length=50),
        ),
        migrations.AddField(
            model_name='conceptocostotrabajador',
            name='incluye_en_total',
            field=models.BooleanField(default=True, help_text='Si es falso, el monto es informativo y no suma al costo (p. ej. TOTAL_LIQUIDADO).'),
        ),
        migrations.AddConstraint(
            model_name='costotrabajadordetalle',
            constraint=models.UniqueConstraint(fields=('costo_trabajador', 'concepto'), name='uq_costo_detalle_concepto'),
        ),
    ]
