# Generated by Django 5.2.17 on 2026-08-25 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remuneraciones', '0007_seed_conceptos_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagoremuneracion',
            options={'ordering': ['-fecha', '-pk'], 'permissions': [('anular_pagoremuneracion', 'Puede anular pagos de remuneración')]},
        ),
        migrations.AddField(
            model_name='pagoremuneracion',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagoremuneracion',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagoremuneracion',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_remuneracion_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagoremuneracion',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
    ]
