from django.urls import path

from rrhh import views

app_name = "rrhh"

urlpatterns = [
    path(
        "trabajadores/",
        views.TrabajadorListView.as_view(),
        name="trabajador_lista",
    ),
    path(
        "trabajadores/nuevo/",
        views.TrabajadorCreateView.as_view(),
        name="trabajador_crear",
    ),
    path(
        "trabajadores/<int:pk>/",
        views.TrabajadorDetailView.as_view(),
        name="trabajador_detalle",
    ),
    path(
        "trabajadores/<int:pk>/editar/",
        views.TrabajadorUpdateView.as_view(),
        name="trabajador_editar",
    ),
    path(
        "trabajadores/<int:pk>/desactivar/",
        views.TrabajadorDesactivarView.as_view(),
        name="trabajador_desactivar",
    ),
    path(
        "trabajadores/<int:trabajador_id>/contratos/",
        views.ContratoListView.as_view(),
        name="trabajador_contratos",
    ),
    path(
        "trabajadores/<int:trabajador_id>/contratos/nuevo/",
        views.ContratoCreateView.as_view(),
        name="trabajador_contrato_crear",
    ),
    path(
        "cargos/",
        views.CargoListView.as_view(),
        name="cargo_lista",
    ),
    path(
        "cargos/nuevo/",
        views.CargoCreateView.as_view(),
        name="cargo_crear",
    ),
    path(
        "cargos/<int:pk>/editar/",
        views.CargoUpdateView.as_view(),
        name="cargo_editar",
    ),
    path(
        "contratos/",
        views.ContratoListView.as_view(),
        name="contrato_lista",
    ),
    path(
        "contratos/nuevo/",
        views.ContratoCreateView.as_view(),
        name="contrato_crear",
    ),
    path(
        "contratos/<int:pk>/",
        views.ContratoDetailView.as_view(),
        name="contrato_detalle",
    ),
    path(
        "contratos/<int:pk>/editar/",
        views.ContratoUpdateView.as_view(),
        name="contrato_editar",
    ),
    path(
        "contratos/<int:pk>/anexos/",
        views.ContratoDetailView.as_view(),
        name="anexo_lista",
    ),
    path(
        "contratos/<int:contrato_id>/anexos/nuevo/",
        views.AnexoContratoCreateView.as_view(),
        name="anexo_crear",
    ),
    path(
        "anexos/<int:pk>/editar/",
        views.AnexoContratoUpdateView.as_view(),
        name="anexo_editar",
    ),
]
