# Generated by Django 5.2.17 on 2026-08-24 18:50

import core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=15, validators=[core.validators.validar_rut])),
                ('rut_normalizado', models.CharField(editable=False, max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_documento', models.DateField(db_index=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(default='FACTURA', max_length=30)),
                ('numero', models.CharField(max_length=50)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tasa_iva_snapshot', models.DecimalField(decimal_places=6, default=Decimal('0.190000'), max_digits=8)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('PARCIAL', 'Pago parcial'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='REGISTRADO', max_length=15)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='facturacion/compras/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='core.centrocosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('ACTIVA', 'Activa'), ('TERMINADA', 'Terminada'), ('SUSPENDIDA', 'Suspendida')], default='PLANIFICADA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='core.centrocosto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to='facturacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_emision', models.DateField(db_index=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('FACTURA_EXENTA', 'Factura exenta'), ('NOTA_CREDITO', 'Nota de crédito'), ('NOTA_DEBITO', 'Nota de débito'), ('BOLETA', 'Boleta'), ('OTRO', 'Otro')], max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tasa_iva_snapshot', models.DecimalField(decimal_places=6, default=Decimal('0.190000'), max_digits=8)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('PARCIAL', 'Pago parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='EMITIDA', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='facturacion.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='facturacion.obra')),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='PagoDocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('medio_pago', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='facturacion.documentocompra')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=15, validators=[core.validators.validar_rut])),
                ('rut_normalizado', models.CharField(editable=False, max_length=12, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_compra', to='facturacion.proveedor'),
        ),
        migrations.CreateModel(
            name='CobroDocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('medio_pago', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='facturacion.documentotributario')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_cobro_documento_monto')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.UniqueConstraint(fields=('tipo_documento', 'numero'), name='uq_documento_venta_tipo_numero'),
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.CheckConstraint(condition=models.Q(('neto__gte', 0)), name='ck_documento_venta_neto'),
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.CheckConstraint(condition=models.Q(('iva__gte', 0)), name='ck_documento_venta_iva'),
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_documento_venta_total'),
        ),
        migrations.AddConstraint(
            model_name='pagodocumentocompra',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pago_compra_monto'),
        ),
        migrations.AddConstraint(
            model_name='documentocompra',
            constraint=models.UniqueConstraint(fields=('proveedor', 'tipo_documento', 'numero'), name='uq_documento_compra'),
        ),
        migrations.AddConstraint(
            model_name='documentocompra',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='ck_documento_compra_total'),
        ),
    ]
