# Generated by Django 5.2.17 on 2026-08-28 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_categorias_base(apps, schema_editor):
    CategoriaCompra = apps.get_model("facturacion", "CategoriaCompra")
    categorias = [
        ("MAT_MATERIALES", "Materiales"),
        ("GAS_COMBUSTIBLE", "Combustible"),
        ("SER_FLETES", "Fletes"),
        ("SER_SEGUROS", "Seguros"),
        ("SER_ASESORIAS", "Asesorías"),
        ("ARR_MAQ_VEHICULOS", "Arriendos"),
        ("GAS_GENERALES", "Gastos generales"),
        ("OTROS", "Otros gastos"),
        ("SIN_CLASIFICAR", "Sin clasificar"),
    ]
    for orden, (codigo, nombre) in enumerate(categorias, start=1):
        CategoriaCompra.objects.update_or_create(
            codigo=codigo,
            defaults={"nombre": nombre, "orden": orden, "activa": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_cobro_venta_anulacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='documentocompra',
            name='categoria_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='facturacion.categoriacompra'),
        ),
        migrations.RunPython(crear_categorias_base, migrations.RunPython.noop),
    ]
