# Generated by Django 5.2.17 on 2026-08-24 18:50

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_contrato', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo fijo'), ('OBRA_FAENA', 'Obra o faena'), ('OTRO', 'Otro')], default='INDEFINIDO', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('sueldo_base_inicial', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('SUSPENDIDO', 'Suspendido'), ('TERMINADO', 'Terminado')], default='VIGENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='rrhh.cargo')),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='core.centrocosto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['trabajador__nombre_completo', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AnexoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_documento', models.DateField()),
                ('fecha_vigencia', models.DateField()),
                ('tipo', models.CharField(choices=[('CAMBIO_SUELDO', 'Cambio de sueldo'), ('CAMBIO_CARGO', 'Cambio de cargo'), ('CAMBIO_CENTRO_COSTO', 'Cambio de centro de costo'), ('OTRO', 'Otro')], max_length=30)),
                ('nuevo_sueldo_base', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='rrhh/anexos/%Y/%m/')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nuevo_centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos_nuevo_centro', to='core.centrocosto')),
                ('nuevo_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anexos_nuevo_cargo', to='rrhh.cargo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='rrhh.contrato')),
            ],
            options={
                'ordering': ['contrato', 'fecha_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('rut', models.CharField(max_length=15, validators=[core.validators.validar_rut])),
                ('rut_normalizado', models.CharField(editable=False, max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trabajador',
                'verbose_name_plural': 'trabajadores',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='rrhh.trabajador'),
        ),
        migrations.AddIndex(
            model_name='trabajador',
            index=models.Index(fields=['nombre_completo'], name='idx_trabajador_nombre'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('sueldo_base_inicial__gte', 0)), name='ck_contrato_sueldo_no_negativo'),
        ),
    ]
