# Generated by Django 5.2.17 on 2026-08-24 19:13

import rrhh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('rrhh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexocontrato',
            options={'ordering': ['contrato', 'fecha_vigencia'], 'verbose_name': 'anexo de contrato', 'verbose_name_plural': 'anexos de contrato'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nombre'], 'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['trabajador__nombre_completo', '-fecha_inicio'], 'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
        migrations.RemoveConstraint(
            model_name='contrato',
            name='ck_contrato_sueldo_no_negativo',
        ),
        migrations.AlterField(
            model_name='anexocontrato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=rrhh.models.anexos_upload_to),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.CheckConstraint(condition=models.Q(('sueldo_base_inicial__gt', 0)), name='ck_contrato_sueldo_positivo'),
        ),
    ]
